# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pplwhohavesolvedalgo',
            old_name='user',
            new_name='solver',
        ),
    ]
