# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 08:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0002_auto_20160226_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='pplwhohavesolvedalgo',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 26, 8, 48, 57, 359882, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
