# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0003_pplwhohavesolvedalgo_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pplwhohavesolvedalgo',
            name='solver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.UserProfile'),
        ),
    ]
