# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 03:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.IntegerField(null=True)),
                ('following', models.IntegerField(null=True)),
                ('public_repos', models.IntegerField(null=True)),
                ('html_url', models.URLField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15)),
                ('seeking', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Both', 'Both')], max_length=15)),
                ('github_username', models.CharField(blank=True, max_length=30, null=True)),
                ('favorite_programming_language', models.CharField(blank=True, choices=[('Python', 'Python'), ('Java', 'Java'), ('PHP', 'PHP'), ('JavaScript', 'JavaScript'), ('C++', 'C++'), ('Swift', 'Swift'), ('Objective-C', 'Objective-C'), ('C', 'C')], max_length=50)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=profiles.models.user_directory_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
