# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 04:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20160226_0434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='ethnicity',
            new_name='race',
        ),
    ]
