# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_auto_20160226_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='oneLikesTwo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='twoLikesOne',
            field=models.BooleanField(default=False),
        ),
    ]
